[package]
name = "module_test"
version = "0.1.0"
authors = ["Richard Tung <zqdbyct@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
